name: Build and Release Go Project

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Install dependencies
        run: go install github.com/goreleaser/goreleaser@latest

      - name: Run tests
        run: make test

      - name: Build project
        run: make release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/gtc
